dist: trusty
sudo: required
group: edge

language: java
jdk: openjdk8

addons:
  apt:
    packages:
      # for gRPC
      - autoconf
      - build-essential
      - libtool
  ssh_known_hosts:
    - localhost
    - 0.0.0.0

install:
  # accept own key to start services locally via ssh
  - ssh-keygen -t dsa -N "" -f $HOME/.ssh/id_dsa
  - cat $HOME/.ssh/id_dsa.pub >> $HOME/.ssh/authorized_keys
  - chmod 600 $HOME/.ssh/authorized_keys

  # set up Hadoop
  - export HADOOP_VERSION=2.7.4
  - HADOOP_ARCHIVE=$HOME/hadoop-$HADOOP_VERSION.tar.gz
  - wget --no-verbose --output-document $HADOOP_ARCHIVE http://archive.apache.org/dist/hadoop/core/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz
  - tar --extract --file $HADOOP_ARCHIVE --directory $HOME
  - export HADOOP_HOME=$HOME/hadoop-$HADOOP_VERSION
  - rm $HADOOP_ARCHIVE

  # build gRPC
  - export GRPC_VERSION=1.6.1
  - export PROTOBUF_VERSION=3.4.0
  - cd $HOME
  - git clone -b v$GRPC_VERSION https://github.com/grpc/grpc
  - export GRPC_HOME=$HOME/grpc
  - cd $GRPC_HOME
  - git submodule update --init
  - cd third_party/protobuf && git checkout tags/v$PROTOBUF_VERSION && cd ../../
  - make -j2

  # make the built libraries available transparently
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$GRPC_HOME/libs/opt:$GRPC_HOME/third_party/protobuf/src/.libs"
  - cd $TRAVIS_BUILD_DIR

  # finally build the thing
  - mvn clean install --define protobuf.version=$PROTOBUF_VERSION --define protoc.bin=$GRPC_HOME/third_party/protobuf/src/protoc --define protobuf.include.dir=$GRPC_HOME/third_party/protobuf/src --define protobuf.lib.dir=$GRPC_HOME/third_party/protobuf/src/.libs --define grpc.version=$GRPC_VERSION --define grpc.plugin=$GRPC_HOME/bins/opt/grpc_cpp_plugin --define grpc.include.dir=$GRPC_HOME/include --define grpc.lib.dir=$GRPC_HOME/libs/opt --define hadoop.version=$HADOOP_VERSION
  - cd $TRAVIS_BUILD_DIR

script:
  # configure Hadoop and run the grep job
  - ./scripts/travis/hadoop_grep.sh
