dist: trusty
sudo: false

language: java
jdk: oraclejdk8

addons:
  apt:
    packages:
      # for gRPC
      - autoconf
      - build-essential
      - libtool
  ssh_known_hosts:
    - localhost
    - 0.0.0.0

# override the initial `mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V` command,
# because this is part of Travis' dependencies installation and would fail because we need to install custom dependencies
install:
  # accept own key to start services locally via ssh
  #- mkdir -p $HOME/.ssh
  #- ssh-keygen -t dsa -N "" -f $HOME/.ssh/id_dsa
  #- cat $HOME/.ssh/id_dsa.pub >> $HOME/.ssh/authorized_keys
  #- chmod 600 $HOME/.ssh/authorized_keys
  #- ssh-keyscan -vvv -t dsa localhost >> $HOME/.ssh/known_hosts
  #- ssh-keyscan -vvv -t dsa 0.0.0.0 >> $HOME/.ssh/known_hosts

  # set up Hadoop
  - export HADOOP_VERSION=2.7.2
  - HADOOP_ARCHIVE=$HOME/hadoop-$HADOOP_VERSION.tar.gz
  - wget --no-verbose --output-document $HADOOP_ARCHIVE https://github.com/robert-schmidtke/hadoop/releases/download/release-$HADOOP_VERSION-nodeprecatedfilestatus/hadoop-$HADOOP_VERSION.tar.gz
  - tar --extract --file $HADOOP_ARCHIVE --directory $HOME
  - export HADOOP_HOME=$HOME/hadoop-$HADOOP_VERSION
  - rm $HADOOP_ARCHIVE

  # build gRPC
  - export GRPC_VERSION=1.0.1
  - export PROTOBUF_VERSION=3.0.0
  - cd $HOME
  - git clone -b v$GRPC_VERSION https://github.com/grpc/grpc
  - export GRPC_HOME=$HOME/grpc
  - cd $GRPC_HOME
  - git submodule update --init
  # the protobuf branch specified in gRPC (at least in v1.0.1) is not available anymore
  - cd third_party/protobuf && git checkout tags/v$PROTOBUF_VERSION && cd ../../
  - make -j2
  - cd $TRAVIS_BUILD_DIR

  # build the adapter
  - mvn install --define hadoop.version=$HADOOP_VERSION --define protobuf.version=$PROTOBUF_VERSION --define protoc.bin=$GRPC_HOME/third_party/protobuf/src/protoc --define protobuf.include.dir=$GRPC_HOME/third_party/protobuf/src --define protobuf.lib.dir=$GRPC_HOME/third_party/protobuf/src/.libs --define grpc.version=$GRPC_VERSION --define grpc.plugin=$GRPC_HOME/bins/opt/grpc_cpp_plugin --define grpc.include.dir=$GRPC_HOME/include --define grpc.lib.dir=$GRPC_HOME/libs/opt

script:
  # configure Hadoop and run the grep job
  - ./src/test/scripts/hadoop_grep.sh
