dist: trusty
sudo: required

language: java
jdk: openjdk8

addons:
  apt:
    packages:
      # for gRPC
      - autoconf
      - build-essential
      - libtool
  ssh_known_hosts:
    - localhost
    - 0.0.0.0

install:
  # accept own key to start services locally via ssh
  - ssh-keygen -t dsa -N "" -f $HOME/.ssh/id_dsa
  - cat $HOME/.ssh/id_dsa.pub >> $HOME/.ssh/authorized_keys
  - chmod 600 $HOME/.ssh/authorized_keys

  # set up Hadoop
  - export HADOOP_VERSION=2.7.2
  - HADOOP_ARCHIVE=$HOME/hadoop-$HADOOP_VERSION.tar.gz
  - wget --no-verbose --output-document $HADOOP_ARCHIVE https://github.com/robert-schmidtke/hadoop/releases/download/release-$HADOOP_VERSION-nodeprecatedfilestatus/hadoop-$HADOOP_VERSION.tar.gz
  - tar --extract --file $HADOOP_ARCHIVE --directory $HOME
  - export HADOOP_HOME=$HOME/hadoop-$HADOOP_VERSION
  - rm $HADOOP_ARCHIVE

  # set up Flink
  - export FLINK_VERSION=1.1.3
  - export FLINK_HADOOP_VERSION=27
  - export FLINK_SCALA_VERSION=2.10
  - FLINK_ARCHIVE=$HOME/flink-$FLINK_VERSION.tgz
  - wget --no-verbose --output-document $FLINK_ARCHIVE http://archive.apache.org/dist/flink/flink-${FLINK_VERSION}/flink-${FLINK_VERSION}-bin-hadoop${FLINK_HADOOP_VERSION}-scala_${FLINK_SCALA_VERSION}.tgz
  - tar --extract --file $FLINK_ARCHIVE --directory $HOME
  - export FLINK_HOME=$HOME/flink-$FLINK_VERSION
  - rm $FLINK_ARCHIVE

  # build gRPC
  - export GRPC_VERSION=1.0.1
  - export PROTOBUF_VERSION=3.0.0
  - cd $HOME
  - git clone -b v$GRPC_VERSION https://github.com/grpc/grpc
  - export GRPC_HOME=$HOME/grpc
  - cd $GRPC_HOME
  - git submodule update --init
  # the protobuf branch specified in gRPC (at least in v1.0.1) is not available anymore
  - cd third_party/protobuf && git checkout tags/v$PROTOBUF_VERSION && cd ../../
  - make -j2

  # make the built libraries available transparently
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$GRPC_HOME/libs/opt:$GRPC_HOME/third_party/protobuf/src/.libs"
  - cd $TRAVIS_BUILD_DIR

  # we need an unreleased version of the maven-shade-plugin because it fixes resource relocation
  - git clone https://github.com/apache/maven-plugins.git
  - cd maven-plugins/maven-shade-plugin
  - git checkout 3964d2a2c3b5d2c3b73b8685755e772cfabeea40
  - mvn install
  - cd $TRAVIS_BUILD_DIR

  # build the agent
  - cd sfs-agent
  - mvn install --define protobuf.version=$PROTOBUF_VERSION --define protoc.bin=$GRPC_HOME/third_party/protobuf/src/protoc --define protobuf.include.dir=$GRPC_HOME/third_party/protobuf/src --define protobuf.lib.dir=$GRPC_HOME/third_party/protobuf/src/.libs --define grpc.version=$GRPC_VERSION --define grpc.plugin=$GRPC_HOME/bins/opt/grpc_cpp_plugin --define grpc.include.dir=$GRPC_HOME/include --define grpc.lib.dir=$GRPC_HOME/libs/opt
  - cd $TRAVIS_BUILD_DIR

  # build the adapter
  - cd sfs-adapter
  - mvn install --define hadoop.version=$HADOOP_VERSION
  - cd $TRAVIS_BUILD_DIR

script:
  # configure Hadoop and run the grep job
  - ./scripts/travis/hadoop_grep.sh
